name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-hub:
    runs-on: ubuntu-latest
    container:
      image: jinaai/jina:master-standard
      options: "--entrypoint /bin/bash"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: push
        run: jina hub push --force ${{ secrets.HUBBLE_UUID }} --secret ${{ secrets.HUBBLE_SECRET }} .